environment:
  matrix:
    - LIB_TYPE: static
      CONFIG: auto
      CC: gcc
      THREADING: pthreads

    - LIB_TYPE: shared
      CONFIG: x86_64
      CC: clang
      AR: llvm-ar
      AS: llvm-as
      THREADING: pthreads

    - LIB_TYPE: static
      CONFIG: auto
      CC: clang
      AR: llvm-ar
      AS: llvm-as
      THREADING: openmp

install:
- if [%CC%]==[gcc] set "PATH=C:\msys64\mingw64\bin;C:\msys64\bin;%PATH%"
- if [%CC%]==[clang] set "PATH=C:\Program Files\LLVM\bin;C:\msys64\bin;%CPATH%"
- if [%CC%]==[clang] call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build_script:
- if [%LIB_TYPE%]==[shared] set "CONFIGURE_OPTS=%CONFIGURE_OPTS% --enable-shared --disable-static"
- if [%LIB_TYPE%]==[static] set "CONFIGURE_OPTS=%CONFIGURE_OPTS% --disable-shared --enable-static"
- set RANLIB=echo
- set LIBPTHREAD=
- set "PATH=%PATH%;C:\projects\blis\lib\%CONFIG%"
- set "CFLAGS=-Wno-macro-redefined"
- bash -lc "cd /c/projects/blis && ./configure %CONFIGURE_OPTS% --enable-cblas --enable-threading=%THREADING% --enable-arg-max-hack --prefix=/c/blis %CONFIG%"
- bash -lc "cd /c/projects/blis && mingw32-make -j4 V=1"
- bash -lc "cd /c/projects/blis && mingw32-make install"
- ps: Compress-Archive -Path C:\blis -DestinationPath C:\blis.zip
- ps: Push-AppveyorArtifact C:\blis.zip

test_script:
- if [%LIB_TYPE%]==[shared] set "TEST_TARGET=checkblis-fast"
- if [%LIB_TYPE%]==[static] set "TEST_TARGET=check"
- bash -lc "cd /c/projects/blis && mingw32-make %TEST_TARGET% -j4 V=1"

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
