environment:
  matrix:
    - LIB_TYPE: static
      CONFIG: auto
      CC: gcc

    - LIB_TYPE: shared
      CONFIG: x86_64
      CC: clang
      AR: llvm-ar
      AS: llvm-as

    - LIB_TYPE: static
      CONFIG: auto
      CC: clang
      AR: llvm-ar
      AS: llvm-as

install:
- if [%CC%]==[clang] set "CONDA_INSTALL_LOCN=C:\\Miniconda36-x64"
- if [%CC%]==[clang] call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
- if [%CC%]==[clang] conda update --yes --quiet conda
- if [%CC%]==[clang] conda config --add channels conda-forge
- if [%CC%]==[clang] conda install --yes clangdev posix m2-make
- if [%CC%]==[clang] call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
- if [%CC%]==[clang] set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
- if [%CC%]==[clang] set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%"
- if [%CC%]==[gcc] set "PATH=C:\msys64\mingw64\bin;C:\msys64\bin;%PATH%"
- if [%CC%]==[clang] set "ACTIVATE=source activate &&"

build_script:
- if [%LIB_TYPE%]==[shared] set "CONFIGURE_OPTS=%CONFIGURE_OPTS% --enable-shared --disable-static"
- if [%LIB_TYPE%]==[static] set "CONFIGURE_OPTS=%CONFIGURE_OPTS% --disable-shared --enable-static"
- set RANLIB=echo
- set LIBPTHREAD=
- set "PATH=%PATH%;C:\projects\blis\lib\%CONFIG%"
- set "CFLAGS=-Wno-macro-redefined"
- bash -lc "%ACTIVATE% cd /c/projects/blis && ./configure %CONFIGURE_OPTS% --enable-cblas --disable-threading --enable-arg-max-hack --prefix=/c/blis %CONFIG%"
- bash -lc "%ACTIVATE% cd /c/projects/blis && make -j4 V=1"
- bash -lc "%ACTIVATE% cd /c/projects/blis && make install"
- ps: Compress-Archive -Path C:\blis -DestinationPath C:\blis.zip
- ps: Push-AppveyorArtifact C:\blis.zip

test_script:
- if [%LIB_TYPE%]==[shared] set "TEST_TARGET=checkblis-fast"
- if [%LIB_TYPE%]==[static] set "TEST_TARGET=check"
- bash -lc "source activate && cd /c/projects/blis && make %TEST_TARGET% -j4 V=1"

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
