language: c
sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - OUT_OF_TREE=1 RUN_TEST=0 THREADING="none" BUILD_CONFIG="auto"
  - OUT_OF_TREE=0 RUN_TEST=1 THREADING="none" BUILD_CONFIG="auto"
  - OUT_OF_TREE=0 RUN_TEST=1 THREADING="none" BUILD_CONFIG="penryn"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="none" BUILD_CONFIG="sandybridge"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="none" BUILD_CONFIG="haswell"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="none" BUILD_CONFIG="knl"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="none" BUILD_CONFIG="bulldozer"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="none" BUILD_CONFIG="piledriver"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="none" BUILD_CONFIG="steamroller"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="none" BUILD_CONFIG="excavator"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="none" BUILD_CONFIG="zen"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="openmp" BUILD_CONFIG="auto"
  - OUT_OF_TREE=0 RUN_TEST=0 THREADING="pthreads" BUILD_CONFIG="auto"
  
matrix:
  allow_failures:
    - env: RUN_TEST=0 THREADING="none" BUILD_CONFIG="knl"
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      env: RUN_TEST=1 THREADING="none" BUILD_CONFIG="penryn"
    - os: osx
      env: RUN_TEST=0 THREADING="none" BUILD_CONFIG="sandybridge"
    - os: osx
      env: RUN_TEST=0 THREADING="none" BUILD_CONFIG="haswell"
    - os: osx
      env: RUN_TEST=0 THREADING="none" BUILD_CONFIG="knl"
    - os: osx
      env: RUN_TEST=0 THREADING="none" BUILD_CONFIG="bulldozer"
    - os: osx
      env: RUN_TEST=0 THREADING="none" BUILD_CONFIG="piledriver"
    - os: osx
      env: RUN_TEST=0 THREADING="none" BUILD_CONFIG="steamroller"
    - os: osx
      env: RUN_TEST=0 THREADING="none" BUILD_CONFIG="excavator"
    - os: osx
      env: RUN_TEST=0 THREADING="none" BUILD_CONFIG="zen"
    - os: osx
      env: RUN_TEST=0 THREADING="openmp" BUILD_CONFIG="auto"

install:
  - if [ "$CC" = "gcc" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC="gcc-5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - clang
    
script:
  - export DIST_PATH=.
  - pwd
  - if [ $OUT_OF_TREE -eq 1 ]; then mkdir oot; cd oot; export DIST_PATH=..; fi
  - pwd
  - $DIST_PATH/configure -t $THREADING CC=$CC $BUILD_CONFIG
  - pwd
  - $CC --version
  - pwd
  - make -j 2
  - export BLIS_IC_NT=2
  - export BLIS_JC_NT=1
  - export BLIS_IR_NT=1
  - export BLIS_JR_NT=1
  - if [ $RUN_TEST -eq 1 ]; then travis_wait 30 make BLIS_ENABLE_TEST_OUTPUT=yes test; fi
  - if [ $RUN_TEST -eq 1 ]; then $DIST_PATH/build/check-test.sh ./output.testsuite; fi

