language: c
sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - OOT=1 TEST=0 THR="none" CONFIG="auto"
  - OOT=0 TEST=1 THR="none" CONFIG="auto"
  - OOT=0 TEST=1 THR="none" CONFIG="penryn"
  - OOT=0 TEST=0 THR="none" CONFIG="sandybridge"
  - OOT=0 TEST=0 THR="none" CONFIG="haswell"
  - OOT=0 TEST=0 THR="none" CONFIG="knl"
  - OOT=0 TEST=0 THR="none" CONFIG="bulldozer"
  - OOT=0 TEST=0 THR="none" CONFIG="piledriver"
  - OOT=0 TEST=0 THR="none" CONFIG="steamroller"
  - OOT=0 TEST=0 THR="none" CONFIG="excavator"
  - OOT=0 TEST=0 THR="none" CONFIG="zen"
  - OOT=0 TEST=0 THR="openmp" CONFIG="auto"
  - OOT=0 TEST=0 THR="pthreads" CONFIG="auto"
  
matrix:
  allow_failures:
    - env: OOT=0 TEST=0 THR="none" CONFIG="knl"
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      env: OOT=0 TEST=1 THR="none" CONFIG="penryn"
    - os: osx
      env: OOT=0 TEST=0 THR="none" CONFIG="sandybridge"
    - os: osx
      env: OOT=0 TEST=0 THR="none" CONFIG="haswell"
    - os: osx
      env: OOT=0 TEST=0 THR="none" CONFIG="knl"
    - os: osx
      env: OOT=0 TEST=0 THR="none" CONFIG="bulldozer"
    - os: osx
      env: OOT=0 TEST=0 THR="none" CONFIG="piledriver"
    - os: osx
      env: OOT=0 TEST=0 THR="none" CONFIG="steamroller"
    - os: osx
      env: OOT=0 TEST=0 THR="none" CONFIG="excavator"
    - os: osx
      env: OOT=0 TEST=0 THR="none" CONFIG="zen"
    - os: osx
      env: OOT=0 TEST=0 THR="openmp" CONFIG="auto"

install:
  - if [ "$CC" = "gcc" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC="gcc-5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - clang
    
script:
  - export DIST_PATH=.
  - pwd
  - if [ $OOT -eq 1 ]; then mkdir oot; cd oot; export DIST_PATH=..; fi
  - pwd
  - $DIST_PATH/configure -t $THR CC=$CC $CONFIG
  - pwd
  - $CC --version
  - pwd
  - make -j 2
  - export BLIS_IC_NT=2
  - export BLIS_JC_NT=1
  - export BLIS_IR_NT=1
  - export BLIS_JR_NT=1
  - if [ $TEST -eq 1 ]; then travis_wait 30 make BLIS_ENABLE_TEST_OUTPUT=yes test; fi
  - if [ $TEST -eq 1 ]; then $DIST_PATH/build/check-test.sh ./output.testsuite; fi

